{
  "/Login" : "Login",
  "/Logout": "Logout",
  "/PostUserFeed": "PostUserFeed",
  "/RepostUserFeed": "RepostUserFeed",
  "/SubscribeUser": "SubscribeUser",
  "/UnsubscribeUser": "UnsubscribeUser",
  "/GetUserFollower": "GetUserFollower",
  "/UserFeedTimeline":"UserFeedTimeline",
  "/ReadUserFeed":"ReadUserFeed",
  "/DeleteUserFeed":"DeleteUserFeed",
  "/ReadFeedByUser":"ReadFeedByUser",
  "/ReadUserFeedMetadata":"ReadUserFeedMetadata",
  "/ReadUserFeedReposts":"ReadUserFeedReposts",
  "/UpdateUserFeed":"UpdateUserFeed",
  "/CommentUserFeed":"CommentUserFeed",
  "/ReadUserFeedComment":"ReadUserFeedComment"
    ,
  "/PostGroupFeed": "PostGroupFeed",
  "/RepostGroupFeed": "RepostGroupFeed",
  "/SubscribeGroup": "SubscribeGroup",
  "/UnsubscribeGroup": "UnsubscribeGroup",
  "/GetGroupFollower": "GetGroupFollower",
  "/GroupFeedTimeline":"GroupFeedTimeline",
  "/ReadGroupFeed":"ReadGroupFeed",
  "/DeleteGroupFeed":"DeleteGroupFeed",
  "/ReadFeedByGroup":"ReadFeedByGroup",
  "/ReadGroupFeedMetadata":"ReadGroupFeedMetadata",
  "/ReadGroupFeedReposts":"ReadGroupFeedReposts",
  "/UpdateGroupFeed":"UpdateGroupFeed",
  "/CommentGroupFeed":"CommentGroupFeed",
  "/ReadGroupFeedComment":"ReadGroupFeedComment"
}