package com.rapidbackend.socialutil.model;
/**
*  Generated By JavaModelGenerator at Dec 10, 2013 1:42:26 PM
**/
public class City extends com.rapidbackend.core.model.DbRecord {
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    private String come;
    
    
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public String getCome(){
        return come;
    }
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public void setCome(String come){
        this.come = come;
    }
    
}