package com.rapidbackend.socialutil.model;
/**
*  Generated By JavaModelGenerator at Dec 10, 2013 1:42:26 PM
**/
public class Groupfeedcomment extends com.rapidbackend.socialutil.model.reserved.CommentBase {
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    private Float where;
    
    
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public Float getWhere(){
        return where;
    }
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public void setWhere(Float where){
        this.where = where;
    }
    
}