package com.rapidbackend.socialutil.model;
/**
*  Generated By JavaModelGenerator at Dec 10, 2013 1:42:26 PM
**/
public class Group extends com.rapidbackend.socialutil.model.reserved.FollowableBase {
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    private String name;
    
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    private Integer type;
    
    
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public String getName(){
        return name;
    }
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public void setName(String name){
        this.name = name;
    }
    
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public Integer getType(){
        return type;
    }
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public void setType(Integer type){
        this.type = type;
    }
    
}