package com.rapidbackend.socialutil.model;
/**
*  Generated By JavaModelGenerator at Dec 10, 2013 1:42:26 PM
**/
public class Groupfeedcontent extends com.rapidbackend.socialutil.model.reserved.FeedContentBase {
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    private String haha;
    
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    private String hoho;
    
    
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public String getHaha(){
        return haha;
    }
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public void setHaha(String haha){
        this.haha = haha;
    }
    
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public String getHoho(){
        return hoho;
    }
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public void setHoho(String hoho){
        this.hoho = hoho;
    }
    
}