package com.rapidbackend.socialutil.model;
/**
*  Generated By JavaModelGenerator at Dec 10, 2013 1:42:26 PM
**/
public class Oauthapplicationuser extends com.rapidbackend.socialutil.model.reserved.Oauthapplicationuser {
    
}