package com.rapidbackend.socialutil.model;
/**
*  Generated By JavaModelGenerator at Dec 10, 2013 1:42:26 PM
**/
public class Profiles extends com.rapidbackend.core.model.DbRecord {
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    private String name;
    
    
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public String getName(){
        return name;
    }
    /**
    **@JavaModelGenerator Dec 10, 2013 1:42:26 PM
    */
    public void setName(String name){
        this.name = name;
    }
    
}