package com.rapidbackend.socialutil.model;
/**
*  Generated By JavaModelGenerator at ${.now}
**/
public class ${classDescriptor.name} extends ${classDescriptor.rootClass} {
    <#list classDescriptor.customFields as field>
    /**
    **@JavaModelGenerator ${.now}
    */
    private ${field.javaType} ${field.name};
    
    </#list>
    
    <#list classDescriptor.customFields as field>
    /**
    **@JavaModelGenerator ${.now}
    */
    public ${field.javaType} get${field.name?cap_first}(){
        return ${field.name};
    }
    /**
    **@JavaModelGenerator ${.now}
    */
    public void set${field.name?cap_first}(${field.javaType} ${field.name}){
        this.${field.name} = ${field.name};
    }
    
    </#list>
}