package com.rapidbackend.socialutil.model.reserved;

import com.rapidbackend.core.model.DbRecord;

public class CommentBase extends DbRecord{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcomment.id
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcomment.created
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    private Long created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcomment.modified
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    private Long modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcomment.feedId
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    private Integer feedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcomment.createdby
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcomment.authorName
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    private String screenName;

    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcomment.content
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcomment.id
     *
     * @return the value of userfeedcomment.id
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcomment.id
     *
     * @param id the value for userfeedcomment.id
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcomment.created
     *
     * @return the value of userfeedcomment.created
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcomment.created
     *
     * @param created the value for userfeedcomment.created
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcomment.modified
     *
     * @return the value of userfeedcomment.modified
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    public Long getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcomment.modified
     *
     * @param modified the value for userfeedcomment.modified
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    public void setModified(Long modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcomment.feedId
     *
     * @return the value of userfeedcomment.feedId
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    public Integer getFeedId() {
        return feedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcomment.feedId
     *
     * @param feedId the value for userfeedcomment.feedId
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    public void setFeedId(Integer feedId) {
        this.feedId = feedId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    

    public String getScreenName() {
        return screenName;
    }

    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcomment.content
     *
     * @return the value of userfeedcomment.content
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcomment.content
     *
     * @param content the value for userfeedcomment.content
     *
     * @mbggenerated Thu Jun 27 17:39:23 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }
}
