package com.rapidbackend.socialutil.model.reserved;

import com.rapidbackend.core.model.DbRecord;

public class Feedsource extends DbRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedsource.url
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedsource.name
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedsource.content
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedsource.url
     *
     * @return the value of feedsource.url
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedsource.url
     *
     * @param url the value for feedsource.url
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedsource.name
     *
     * @return the value of feedsource.name
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedsource.name
     *
     * @param name the value for feedsource.name
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedsource.content
     *
     * @return the value of feedsource.content
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedsource.content
     *
     * @param content the value for feedsource.content
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }
}