package com.rapidbackend.socialutil.model.reserved;

import com.rapidbackend.core.model.DbRecord;

public class FeedContentBase extends DbRecord{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.id
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.userId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.truncated
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Integer truncated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.seedFeedId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Integer seedFeedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.replyToId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Integer replyToId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.replyToScreenName
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private String replyToScreenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.repostToId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Integer repostToFeedId;
    
    

    public Integer getRepostToFeedId() {
        return repostToFeedId;
    }

    public void setRepostToFeedId(Integer repostToFeedId) {
        this.repostToFeedId = repostToFeedId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.repostToUserId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Integer repostToUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.geoEnabled
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Integer geoEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.latitude
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.longitude
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.location
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.sourceId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Integer sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.uniqueId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.modified
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Long modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.created
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private Long created;

    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfeedcontent.content
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.id
     *
     * @return the value of userfeedcontent.id
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.id
     *
     * @param id the value for userfeedcontent.id
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.userId
     *
     * @return the value of userfeedcontent.userId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.userId
     *
     * @param userId the value for userfeedcontent.userId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.truncated
     *
     * @return the value of userfeedcontent.truncated
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Integer getTruncated() {
        return truncated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.truncated
     *
     * @param truncated the value for userfeedcontent.truncated
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setTruncated(Integer truncated) {
        this.truncated = truncated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.seedFeedId
     *
     * @return the value of userfeedcontent.seedFeedId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Integer getSeedFeedId() {
        return seedFeedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.seedFeedId
     *
     * @param seedFeedId the value for userfeedcontent.seedFeedId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setSeedFeedId(Integer seedFeedId) {
        this.seedFeedId = seedFeedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.replyToId
     *
     * @return the value of userfeedcontent.replyToId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Integer getReplyToId() {
        return replyToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.replyToId
     *
     * @param replyToId the value for userfeedcontent.replyToId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setReplyToId(Integer replyToId) {
        this.replyToId = replyToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.replyToScreenName
     *
     * @return the value of userfeedcontent.replyToScreenName
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public String getReplyToScreenName() {
        return replyToScreenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.replyToScreenName
     *
     * @param replyToScreenName the value for userfeedcontent.replyToScreenName
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    
    public void setReplyToScreenName(String replyToScreenName) {
        this.replyToScreenName = replyToScreenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.repostToId
     *
     * @return the value of userfeedcontent.repostToId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     *
    public Integer getRepostToId() {
        return repostToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.repostToId
     *
     * @param repostToId the value for userfeedcontent.repostToId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     *
    public void setRepostToId(Integer repostToId) {
        this.repostToId = repostToId;
    }*/

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.repostToUserId
     *
     * @return the value of userfeedcontent.repostToUserId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Integer getRepostToUserId() {
        return repostToUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.repostToUserId
     *
     * @param repostToUserId the value for userfeedcontent.repostToUserId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setRepostToUserId(Integer repostToUserId) {
        this.repostToUserId = repostToUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.geoEnabled
     *
     * @return the value of userfeedcontent.geoEnabled
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Integer getGeoEnabled() {
        return geoEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.geoEnabled
     *
     * @param geoEnabled the value for userfeedcontent.geoEnabled
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setGeoEnabled(Integer geoEnabled) {
        this.geoEnabled = geoEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.latitude
     *
     * @return the value of userfeedcontent.latitude
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.latitude
     *
     * @param latitude the value for userfeedcontent.latitude
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.longitude
     *
     * @return the value of userfeedcontent.longitude
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.longitude
     *
     * @param longitude the value for userfeedcontent.longitude
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.location
     *
     * @return the value of userfeedcontent.location
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.location
     *
     * @param location the value for userfeedcontent.location
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.sourceId
     *
     * @return the value of userfeedcontent.sourceId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.sourceId
     *
     * @param sourceId the value for userfeedcontent.sourceId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.uniqueId
     *
     * @return the value of userfeedcontent.uniqueId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.uniqueId
     *
     * @param uniqueId the value for userfeedcontent.uniqueId
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.modified
     *
     * @return the value of userfeedcontent.modified
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Long getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.modified
     *
     * @param modified the value for userfeedcontent.modified
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setModified(Long modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.created
     *
     * @return the value of userfeedcontent.created
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.created
     *
     * @param created the value for userfeedcontent.created
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfeedcontent.content
     *
     * @return the value of userfeedcontent.content
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfeedcontent.content
     *
     * @param content the value for userfeedcontent.content
     *
     * @mbggenerated Fri Apr 26 17:18:29 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }
}
