package com.rapidbackend.socialutil.model.reserved;

import com.rapidbackend.core.model.DbRecord;

public class Fileuploaded extends DbRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileuploaded.userid
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileuploaded.fileDescription
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String fileDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileuploaded.fileLocation
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String fileLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileuploaded.userid
     *
     * @return the value of fileuploaded.userid
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileuploaded.userid
     *
     * @param userid the value for fileuploaded.userid
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileuploaded.fileDescription
     *
     * @return the value of fileuploaded.fileDescription
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getFileDescription() {
        return fileDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileuploaded.fileDescription
     *
     * @param fileDescription the value for fileuploaded.fileDescription
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setFileDescription(String fileDescription) {
        this.fileDescription = fileDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileuploaded.fileLocation
     *
     * @return the value of fileuploaded.fileLocation
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getFileLocation() {
        return fileLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileuploaded.fileLocation
     *
     * @param fileLocation the value for fileuploaded.fileLocation
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setFileLocation(String fileLocation) {
        this.fileLocation = fileLocation;
    }
}