package com.rapidbackend.socialutil.model.reserved;

import com.rapidbackend.core.model.DbRecord;

public class FollowabeFeedBase extends DbRecord{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupfeed.feedId
     *
     * @mbggenerated Thu Jun 27 17:49:33 CST 2013
     */
    private Integer feedId;
    
    private Integer followableId;
    
    private Integer repostToFeedId;
    
    public Integer getRepostToFeedId() {
        return repostToFeedId;
    }

    public void setRepostToFeedId(Integer repostToFeedId) {
        this.repostToFeedId = repostToFeedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupfeed.feedId
     *
     * @return the value of groupfeed.feedId
     *
     * @mbggenerated Thu Jun 27 17:49:33 CST 2013
     */
    public Integer getFeedId() {
        return feedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupfeed.feedId
     *
     * @param feedId the value for groupfeed.feedId
     *
     * @mbggenerated Thu Jun 27 17:49:33 CST 2013
     */
    public void setFeedId(Integer feedId) {
        this.feedId = feedId;
    }

	public Integer getFollowableId() {
		return followableId;
	}

	public void setFollowableId(Integer followableId) {
		this.followableId = followableId;
	}
    
    
}
