package com.rapidbackend.socialutil.model.reserved;

import com.rapidbackend.core.model.DbRecord;

public class Oauthapplicationuser extends DbRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplicationuser.userId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplicationuser.applicationId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private Integer applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplicationuser.accessType
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String accessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplicationuser.code
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplicationuser.uid
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplicationuser.screenName
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String screenName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplicationuser.userId
     *
     * @return the value of oauthapplicationuser.userId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplicationuser.userId
     *
     * @param userId the value for oauthapplicationuser.userId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplicationuser.applicationId
     *
     * @return the value of oauthapplicationuser.applicationId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplicationuser.applicationId
     *
     * @param applicationId the value for oauthapplicationuser.applicationId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplicationuser.accessType
     *
     * @return the value of oauthapplicationuser.accessType
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getAccessType() {
        return accessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplicationuser.accessType
     *
     * @param accessType the value for oauthapplicationuser.accessType
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setAccessType(String accessType) {
        this.accessType = accessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplicationuser.code
     *
     * @return the value of oauthapplicationuser.code
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplicationuser.code
     *
     * @param code the value for oauthapplicationuser.code
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplicationuser.uid
     *
     * @return the value of oauthapplicationuser.uid
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplicationuser.uid
     *
     * @param uid the value for oauthapplicationuser.uid
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplicationuser.screenName
     *
     * @return the value of oauthapplicationuser.screenName
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getScreenName() {
        return screenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplicationuser.screenName
     *
     * @param screenName the value for oauthapplicationuser.screenName
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }
}