package com.rapidbackend.socialutil.model.reserved;

import com.rapidbackend.core.model.DbRecord;

public class Oauthapplication extends DbRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplication.owner
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private Integer owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplication.consumerKey
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String consumerKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplication.name
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplication.description
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplication.icon
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplication.sourceUrl
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String sourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplication.homepage
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String homepage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplication.organization
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplication.callbackUrl
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String callbackUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplication.type
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthapplication.accessType
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String accessType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplication.owner
     *
     * @return the value of oauthapplication.owner
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplication.owner
     *
     * @param owner the value for oauthapplication.owner
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplication.consumerKey
     *
     * @return the value of oauthapplication.consumerKey
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getConsumerKey() {
        return consumerKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplication.consumerKey
     *
     * @param consumerKey the value for oauthapplication.consumerKey
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setConsumerKey(String consumerKey) {
        this.consumerKey = consumerKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplication.name
     *
     * @return the value of oauthapplication.name
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplication.name
     *
     * @param name the value for oauthapplication.name
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplication.description
     *
     * @return the value of oauthapplication.description
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplication.description
     *
     * @param description the value for oauthapplication.description
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplication.icon
     *
     * @return the value of oauthapplication.icon
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplication.icon
     *
     * @param icon the value for oauthapplication.icon
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplication.sourceUrl
     *
     * @return the value of oauthapplication.sourceUrl
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplication.sourceUrl
     *
     * @param sourceUrl the value for oauthapplication.sourceUrl
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplication.homepage
     *
     * @return the value of oauthapplication.homepage
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplication.homepage
     *
     * @param homepage the value for oauthapplication.homepage
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplication.organization
     *
     * @return the value of oauthapplication.organization
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplication.organization
     *
     * @param organization the value for oauthapplication.organization
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setOrganization(String organization) {
        this.organization = organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplication.callbackUrl
     *
     * @return the value of oauthapplication.callbackUrl
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplication.callbackUrl
     *
     * @param callbackUrl the value for oauthapplication.callbackUrl
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplication.type
     *
     * @return the value of oauthapplication.type
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplication.type
     *
     * @param type the value for oauthapplication.type
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthapplication.accessType
     *
     * @return the value of oauthapplication.accessType
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getAccessType() {
        return accessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthapplication.accessType
     *
     * @param accessType the value for oauthapplication.accessType
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setAccessType(String accessType) {
        this.accessType = accessType;
    }
}