package com.rapidbackend.socialutil.model.reserved;

import com.rapidbackend.core.model.DbRecord;

public class Oauthtokenassociation extends DbRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthtokenassociation.userId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthtokenassociation.applicationId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private Integer applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauthtokenassociation.token
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthtokenassociation.userId
     *
     * @return the value of oauthtokenassociation.userId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthtokenassociation.userId
     *
     * @param userId the value for oauthtokenassociation.userId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthtokenassociation.applicationId
     *
     * @return the value of oauthtokenassociation.applicationId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthtokenassociation.applicationId
     *
     * @param applicationId the value for oauthtokenassociation.applicationId
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauthtokenassociation.token
     *
     * @return the value of oauthtokenassociation.token
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauthtokenassociation.token
     *
     * @param token the value for oauthtokenassociation.token
     *
     * @mbggenerated Fri Jun 28 11:59:23 CST 2013
     */
    public void setToken(String token) {
        this.token = token;
    }
}