package com.rapidbackend.socialutil.model.reserved;

import com.rapidbackend.core.model.DbRecord;

public class Subscription extends DbRecord{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersubscription.id
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersubscription.followable
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    private Integer followable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersubscription.follower
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    private Integer follower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersubscription.created
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    private Long created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersubscription.modified
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    private Long modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersubscription.id
     *
     * @return the value of usersubscription.id
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersubscription.id
     *
     * @param id the value for usersubscription.id
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersubscription.followable
     *
     * @return the value of usersubscription.followable
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    public Integer getFollowable() {
        return followable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersubscription.followable
     *
     * @param followable the value for usersubscription.followable
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    public void setFollowable(Integer followable) {
        this.followable = followable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersubscription.follower
     *
     * @return the value of usersubscription.follower
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    public Integer getFollower() {
        return follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersubscription.follower
     *
     * @param follower the value for usersubscription.follower
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    public void setFollower(Integer follower) {
        this.follower = follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersubscription.created
     *
     * @return the value of usersubscription.created
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersubscription.created
     *
     * @param created the value for usersubscription.created
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersubscription.modified
     *
     * @return the value of usersubscription.modified
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    public Long getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersubscription.modified
     *
     * @param modified the value for usersubscription.modified
     *
     * @mbggenerated Mon May 06 16:55:45 CST 2013
     */
    public void setModified(Long modified) {
        this.modified = modified;
    }
}
