package com.rapidbackend.socialutil.model.reserved;


import com.rapidbackend.core.model.DbRecord;

public class UserBase extends DbRecord{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    private Integer id;

    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.screenName
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    private String screenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userUrl
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    private String userUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    private Long created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.modified
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    private Long modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.screenName
     *
     * @return the value of user.screenName
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public String getScreenName() {
        return screenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.screenName
     *
     * @param screenName the value for user.screenName
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userUrl
     *
     * @return the value of user.userUrl
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public String getUserUrl() {
        return userUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userUrl
     *
     * @param userUrl the value for user.userUrl
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public void setUserUrl(String userUrl) {
        this.userUrl = userUrl;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created
     *
     * @return the value of user.created
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created
     *
     * @param created the value for user.created
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.modified
     *
     * @return the value of user.modified
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public Long getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.modified
     *
     * @param modified the value for user.modified
     *
     * @mbggenerated Mon May 06 18:05:42 CST 2013
     */
    public void setModified(Long modified) {
        this.modified = modified;
    }
}
