CREATE  TABLE IF NOT EXISTS `${dbName}`.`testmodel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `intField` INT(11) NULL DEFAULT NULL ,
  `charField` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `longField` BIGINT(20) NULL DEFAULT NULL ,
  `floatField` FLOAT NULL DEFAULT NULL ,
  `textField` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `created` BIGINT(20) NULL DEFAULT NULL ,
  `modified` BIGINT(20) NULL DEFAULT NULL ,
  `varchar` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `float` FLOAT NULL DEFAULT NULL ,
  `where` BIGINT(20) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;